name: Build Spider Plugin

on:
  push:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Gradle
        run: gradle build --no-daemon --stacktrace

      # Собираем все готовые .jar файлы плагина в одну папку
      - name: Prepare Plugin File
        run: |
          mkdir -p ready_plugin
          find build/libs/ -name "*.jar" ! -name "*original*" -exec cp {} ready_plugin/ \;

      # Выкладываем файл на страницу GitHub Actions для скачивания
      - name: Upload Plugin Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Minecraft-Spider-Plugin
          path: ready_plugin/
